services:
  - type: web
    name: plotweaver-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements_simple.txt
    startCommand: uvicorn simple_main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: 1
      - key: MODEL_PATH
        value: ""
      - key: TEST_MODE
        value: "true"
    healthCheckPath: /health
    
  - type: web
    name: plotweaver-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: 1
      - key: API_BASE_URL
        value: "https://plotweaver-api.onrender.com"
